### ISSUE TITLE
All of the Images cannot be rendered.

### ISSUE THREAD

**Issue by BOKYUNGGG** [luciovilla/notion-nextjs-blog#4]
Device : iPhone 11
Browser : safari, chrome

Can you fix it?![image](https://user-images.githubusercontent.com/113874167/232427494-9c5b4ede-0f88-4ed9-995f-9621565a4b9a.png)

**Comment by luciovilla** [comment]
Thanks for flagging this! I fixed the Notion database to use an image URL instead of uploading an image to Notion. It looks like the Notion API provides AWS urls when you upload an image to Notion and it seems to not work on some browsers.

In the meantime, Id suggest using the `Embed URL` option when adding an image: 
![image](https://user-images.githubusercontent.com/4227347/232639380-9cb87681-a581-4463-ab6e-d080927c2aa7.png)
